### ISSUE TITLE
"minimum-peer-connectivity" option being ignored by Validator

### ISSUE THREAD

**Issue by will-gluwa** [hyperledger/sawtooth-core#2383]
Copied from https://jira.hyperledger.org/browse/STL-1709

In our testnet environment, I have --minimum-peer-connectivity set to 1 however, the validators still show DEBUG messages like this:
```
sawtooth-validator-default | [2020-06-17 05:45:23.116 DEBUG gossip] Number of peers (1) below minimum peer threshold (3). Doing topology search.
```
![image-2020-06-16-22-46-18-612](https://user-images.githubusercontent.com/83000144/123486841-af37b480-d5c1-11eb-8470-6614c1f82109.png)

**Comment by will-gluwa** [comment]
Fixed in https://github.com/hyperledger/sawtooth-core/pull/2382

**Comment by arsulegai** [comment]
Can you please add more information to the issue? Example: what is the version of the Sawtooth used while testing.

**Comment by will-gluwa** [comment]
Closing issue as the fix has been merged.
