### ISSUE TITLE
Scheduler in main-thread

### ISSUE THREAD

**Issue by SHWETA2JHA** [hyperledger/sawtooth-core#2450]
I'd like to know where's the py_scheduler.rs in the main thread?

**Comment by arsulegai** [comment]
@SHWETA2JHA can you share more information on what you're looking for? You may want to consider looking into https://github.com/hyperledger/sawtooth-lib for the related code.

**Comment by SHWETA2JHA** [comment]
In version 1.2 we have https://github.com/hyperledger/sawtooth-core/blob/1-2/validator/sawtooth_validator/execution/scheduler_parallel.py and https://github.com/hyperledger/sawtooth-core/blob/1-2/validator/sawtooth_validator/execution/scheduler_serial.py I'm looking for these files (the scheduler) in the main thread. I'm unable to locate these files in the main thread.

**Comment by SHWETA2JHA** [comment]
To be specific I'm looking for the scheduler in the main thread..where is it called from.

**Comment by arsulegai** [comment]
Checkout these files https://github.com/hyperledger/transact/tree/main/libtransact/src/scheduler and https://github.com/hyperledger/sawtooth-lib/blob/main/libsawtooth/src/journal/block_scheduler.rs. Depending on the version you're looking for, you should be able to find the code in one of these places.
